### ISSUE TITLE
Are the limits on line length still necesery?

### ISSUE THREAD

**Issue by refack** [nodejs/Collaborators#1]
1) 50 chars for commit title
2) 72 chars for commit message
3) 80 chars for code line

I'm just asking why? (It's not obvious to me probably because I work on windows, and do most of my editing in GUI tools)

Especially the 80 char per code line, I figure originaly it came from narrow terminal windows, and the assumption that one line should not do too much, but sometimes it leads to very cumbersome constructs:
Examples taken from `configure`
<sup>No disrespect to the author, just some examples from a file I was working with</sup>
```python
valid_os = ('win', 'mac', 'solaris', 'freebsd', 'openbsd', 'linux',
            'android', 'aix')
valid_arch = ('arm', 'arm64', 'ia32', 'mips', 'mipsel', 'ppc', 'ppc64', 'x32',
              'x64', 'x86', 's390', 's390x')
```
or
```python
    try:
      proc = subprocess.Popen(
          shlex.split(pkg_config) + ['--silence-errors', flag, pkg],
          stdout=subprocess.PIPE)
```
while multi operationally lines are considered ok
```python
sys.exit(subprocess.call(gyp_args))
```

Or in documentation files? It's easy to find examples where it was not enforced, and anyway files are rendered to something prettier.

**Comment by jasnell** [comment]
I have made this repository public. I know there is still active discussion about whether this repository is even necessary. It should not have been created until it became clear that there was consensus that it was needed. I for one see absolutely no reason for it to exist as such conversations can be easily had in the nodejs/node, nodejs/ctc, nodejs/tsc, nodejs/NG, or nodejs/node-eps repositories depending on the specific topic.

Given that this particular conversation deals with proposed changes to core policies, the right place to have this discussion is in the nodejs/core repository. Either of of the existing issues can be used, or a new issue created. Or, a PR that proposes specific changes in accordance to our existing processes can be proposed. I'm going to close this issue here. @refack, please direct any further conversation on this topic to the nodejs/node repo.

**Comment by refack** [comment]
@jasnell I'm not going to discuss the issue in the title, but rather my understanding of a forum like this, please read my reply.

> I have made this repository public.

Sure. My mistake.

>I know there is still active discussion about whether this repository is even necessary. It should not have been created until it became clear that there was consensus that it was needed. I for one see absolutely no reason for it to exist as such conversations can be easily had in the nodejs/node, nodejs/ctc, nodejs/tsc, nodejs/NG, or nodejs/node-eps repositories depending on the specific topic.

I agree I was hasty but I did not see any obvious objections in nodejs/TSC#243. Can we call this a pilot?


> Given that this particular conversation deals with proposed changes to core policies, the right place to have this discussion is in the nodejs/core repository. Either of of the existing issues can be used, or a new issue created. Or, a PR that proposes specific changes in accordance to our existing processes can be proposed. I'm going to close this issue here. @refack, please direct any further conversation on this topic to the nodejs/node repo.

As @MylesBorins said "this could also be a great place to move conversations that have a good kernel but are inappropriate or derailing in other environments."
For example this is issue is obviously a bikeshed issue, and I meant it to be a discussion, and used this forum since I was looking for a place to have a discussion that does not seek a conclusion, and does not propose anything.

If you still object to the existence of this forum, even in a pilot basis, I'll remove it.

**Comment by addaleax** [comment]
> If you still object to the existence of this forum, even in a pilot basis, I'll remove it.

Yes, I would recommend that you remove this repo and wait until a consensus-based resolution emerges out of https://github.com/nodejs/TSC/issues/243.

**Comment by refack** [comment]
Ok. I'll document this thread as an example
